platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'


#post_install do |installer|
#
#    puts 'Determining pod project minimal deployment target'
#
#    pods_project = installer.pods_project
#    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
#    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
#    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
#
#    puts 'Minimal deployment target is ' + minimal_deployment_target
#    puts 'Setting each pod deployment target to ' + minimal_deployment_target
#
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings[deployment_target_key] = minimal_deployment_target
#        end
#    end
#end

target 'cj_NativeFlutter_iOSDemo' do
  flutter_application_path = '../cj_nativeflutter_fluttermodule/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
  pod 'CJBaseUIKit',  :subspecs => ['UIColor', 'UINavigationBar']
  pod 'CJBaseUtil',   :subspecs => ['CJDataUtil']
  pod 'CQOverlayKit', :subspecs => ['CQToast', 'CQAlert', 'CQHUD']
  
  pod 'CJDemoModuleLogin/Logic'#,  :path => '~/Project/Gitee/AppLoginCollect’
end
