platform :ios, '8.0'
#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

target 'cj_rn_logindemo' do


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

target 'cj_rn_logindemoTests' do
    
end
